#配置数据库
version: '3.3'

services:
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  service:
    build:
      context: .
      dockerfile: ./elaooe-service/Dockerfile
    image: elaooe-service
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    ports:
      - 3001:3001
  # admin-builder:
  #   build:
  #     context: .
  #     dockerfile: ./elaooe-admin/Dockerfile
  #   image: elaooe-admin-build
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./build/admin/:/app/dist/
volumes:
  db-config:
  db-data:
